name: Sync new Repo dummy
on:
  push:
    paths:
      - 'bundle/**'
      - 'Dockerfiles/bundle.Dockerfile'
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to sync'
        required: true
        type: string
  schedule:
    - cron: '0 0 * * *'  # Adjust the schedule as needed
permissions:
  contents: read
  packages: write
  id-token: write
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout rhods-operator repo
        uses: actions/checkout@v3
        with:
          repository: DevOps-automation-tasks/rhods-operator
          token: ${{ secrets.sync_upstream_token}}
          ref: ${{ github.event.inputs.branch || github.ref_name }}
      - name: Display Files Changed
        run: |
          echo "Files changed in this push:"
          git diff --name-only ${{ github.event.before }} ${{ github.event.after }}
      - name: Checkout RHOAI-Build-Config repo
        uses: actions/checkout@v3
        with:
          repository: DevOps-automation-tasks/RHOAI-Build-Config
          token: ${{ secrets.sync_upstream_token }}
          path: rbc_repo
          ref: ${{ github.event.inputs.branch || github.ref_name }}
      - name: Sync bundle to RBC repo
        run: |
          mkdir -p rbc_repo/bundle/
          cp -r bundle/* rbc_repo/bundle/
          cp Dockerfiles/bundle.Dockerfile rbc_repo/bundle/Dockerfile
          echo "Files synced to RBC repo."
      - name: Update local branch and commit changes
        run: |
          cd rbc_repo
          git fetch origin
          git checkout ${{ github.event.inputs.branch || github.ref_name }}
          git pull origin ${{ github.event.inputs.branch || github.ref_name }}
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Sync bundle changes from rhods-operator repo" || echo "No changes to commit"
      - name: Push changes to RBC repo
        run: |
          cd rbc_repo
          git push origin ${{ github.event.inputs.branch || github.ref_name }}
