name: Get Image SHAs from Quay.io

on:
  workflow_dispatch:

jobs:
  get-shas:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Install Skopeo
        run: |
          sudo apt-get update
          sudo apt-get install -y skopeo
      - name: Log in to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
        
      - name: Retrieve Image SHAs
        id: get-shas
        env:
          QUAY_IO_USERNAME: ${{ secrets.QUAY_USERNAME }}
          QUAY_IO_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
        run: |
          repositories=(
            "opendatahub/kserve-controller:fast"
            "opendatahub/openvino_model_server:stable"
          )
          
          for repo in "${repositories[@]}"; do
            echo "Retrieving SHAs for $repo"
            output=$(skopeo inspect --creds "${QUAY_IO_USERNAME}:${QUAY_IO_PASSWORD}" "docker://quay.io/$repo")
            if [ $? -ne 0 ]; then
              echo "Failed to retrieve manifest for $repo"
              continue
            fi
            sha=$(echo "$output" | jq -r '.Digest')
            echo "SHA for $repo: $sha"
          done
