name: Pull from Upstream and Cherry-pick Patches

on:
  workflow_dispatch:
    inputs:
      upstream_repo:
        description: 'Select Upstream Repository'
        required: true
        type: choice
        options:
          - 'openvinotoolkit/model_server'
          - 'kserve/kserve'
          - 'kserve/modelmesh'
          - 'caikit-tgis-serving'
          - 'openvinotoolkit/openvino'
          - 'vllm-project/vllm'
          - 'caikit/caikit-nlp'
          - 'caikit/caikit'
          - 'odh-model-controller'
          - 'caikit/caikit-tgis-backend'
          - 'caikit-nlp-client'
          - 'kubeflow/model-registry'
      Pull_and_cherrypick:
        description: 'Select Repository to Pull_and_cherrypick'
        required: true
        type: choice
        options:
          - 'Upstream->Midstream(opendatahub-io)'
          - 'Midstream(opendatahub-io)->Downstream(red-hat-data-services)'
      source_branch:
        description: 'Source branch to pull from'
        required: true
      target_branch:
        description: 'Target branch to pull into'
        required: true
      patch_commits:
        description: 'Comma-separated list of commit SHAs to cherry-pick'
        required: true

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  pull_and_cherry_pick:
    runs-on: ubuntu-latest
    outputs: 
        target_repo: ${{ steps.set-repo.outputs.target_org_repo }}
    steps:
    - name: Set repository
      id: set-repo
      run: |
        if [[ "${{ github.event.inputs.upstream_repo }}" == *"/"* ]]; then
          IFS='/' read -r upstreamOwner repoName <<< "${{ github.event.inputs.upstream_repo }}"
        else
          repoName=${{ github.event.inputs.upstream_repo }}
          upstreamOwner=""
        fi
        if [ -n "$upstreamOwner" ] && [[ "${{ github.event.inputs.Pull_and_cherrypick }}" == "Upstream->Midstream(opendatahub-io)" ]]; then
          echo "upstream_org_repo=${{ github.event.inputs.upstream_repo }}"  >> $GITHUB_OUTPUT
          # echo "target_org_repo=opendatahub-io/$repoName" >> $GITHUB_OUTPUT
          echo "target_org_repo=rpancham/$repoName" >> $GITHUB_OUTPUT
        else
          echo "upstream_org_repo=opendatahub-io/$repoName"  >> $GITHUB_OUTPUT
          # echo "target_org_repo=red-hat-data-services/$repoName" >> $GITHUB_OUTPUT
          echo "target_org_repo=rpancham/$repoName" >> $GITHUB_OUTPUT
        fi
    - name: Configure Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        repository: ${{ steps.set-repo.outputs.target_org_repo }}
        token: ${{ secrets.SYNC_UPSTREAM_TOKEN }}
        fetch-depth: 0

    - name: Add upstream repository & create cherry pick branch
      run: |
        if git merge-base --is-ancestor ${{ github.event.inputs.patch_commits }} origin/${{ github.event.inputs.target_branch }}; then
          echo "Commit already exists in the target branch."
          exit 1
        fi
        git remote add upstream https://github.com/${{ steps.set-repo.outputs.upstream_org_repo }}.git
        git fetch upstream
        git checkout upstream/${{ github.event.inputs.source_branch }}
        git switch -c cherry-pick-${{ github.event.inputs.patch_commits }}

    - name: Cherry-pick commits
      run: |
        commits="${{ github.event.inputs.patch_commits }}"
        IFS=',' read -ra commit_array <<< "$commits"
        for commit in "${commit_array[@]}"; do
          if git show --no-patch --format=%P $commit | grep -q ' '; then
            echo "Cherry-picking merge commit $commit"
            git cherry-pick -m 1 "$commit" || (git cherry-pick --abort && exit 1)
          else
            echo "Cherry-picking regular commit $commit"
            git cherry-pick "$commit" || (git cherry-pick --abort && exit 1)
          fi
         
        done

    - name: Push changes to cherry pick branch & Create a PR
      run: |
        git log -n 1 --pretty=format:"%H - %s"
        git push -f origin cherry-pick-${{ github.event.inputs.patch_commits }}
        gh pr create --repo ${{ steps.set-repo.outputs.target_org_repo }} \
          --head cherry-pick-${{ github.event.inputs.patch_commits }} \
          --base ${{ github.event.inputs.target_branch }} \
          --title "Cherry-pick of commits ${{ github.event.inputs.patch_commits }} into ${{ github.event.inputs.target_branch }}" \
          --body "$(echo -e "This is a auto genrated PR, Creating from odh-automation-serving\nCherry-pick of commits ${{ github.event.inputs.patch_commits }} into ${{ github.event.inputs.target_branch }}")"
      env:
        GITHUB_TOKEN: ${{ secrets.SYNC_UPSTREAM_TOKEN }}
